### ISSUE TITLE
Update Application dependency

### ISSUE THREAD

**Issue by SrMouraSilva** [PedalPi/WebService#40]
- [x] abstract_request_handler.py
- [x] bank_handler.py
- [x] banks_handler.py
- [x] component_data_handler.py
- [x] connection_handler.py
- [x] current_data_handler.py
- [x] current_effect_status_handler.py
- [x] current_handler.py
- [x] current_pedalboard_handler.py
- [x] device_name_handler.py
- [x] effect_handler.py
- [x] move_pedalboard_handler.py
- [x] move_bank_handler.py
- [x] param_handler.py
- [x] pedalboard_data_handler.py
  - [x] Notificação de alteração manaual: Alterar pedalboard data handler não causa persistencia
- [x] pedalboard_handler.py
- [x] plugin_handler.py
- [x] plugins_handler.py
- [x] plugins_reload_handler.py

Others

 - [x] ~Remover efeito causa atualização do pedalboard~ Problema no apk, não no webservice

**Comment by SrMouraSilva** [comment]
```
Traceback (most recent call last):
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/webservice/webservice/util/handler_utils.py", line 58, in wrapped
    f(*args, **kwargs)
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/webservice/webservice/util/handler_utils.py", line 58, in wrapped
    f(*args, **kwargs)
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/webservice/webservice/util/handler_utils.py", line 30, in wrapped
    f(*args, **kwargs)
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/webservice/webservice/handler/effect_handler.py", line 59, in delete
    del pedalboard.effects[effect_index]
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/observer/observable_list.py", line 135, in __delitem__
    self.observer(UpdateType.DELETED, item, sliced)
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/model/pedalboard.py", line 103, in _effects_observer
    self._clear_effect(effect)
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/model/pedalboard.py", line 113, in _clear_effect
    self.connections.remove(connection)
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/observer/observable_list.py", line 63, in remove
    self.observer(UpdateType.DELETED, item, index)
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/model/pedalboard.py", line 119, in _connections_observer
    self.observer.on_connection_updated(connection, update_type, pedalboard=self, **kwargs)
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/observer/observer_manager.py", line 77, in on_connection_updated
    observer.on_connection_updated(connection, update_type, pedalboard=pedalboard, **kwargs)
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/observer/autosaver/autosaver.py", line 165, in on_connection_updated
    self.banks_files.save_bank(connection.output.effect.pedalboard.bank)
AttributeError: 'NoneType' object has no attribute 'bank'

[2017-05-28 17:50:52,381] ERROR - 500 DELETE /v1/bank/0/pedalboard/4/effect/0 (127.0.0.1) 48.05ms
[2017-05-28 17:51:08,245] INFO - WebSocket closed - Token 82ab31c2-666d-4a3d-9524-98077559db59
[2017-05-28 17:51:10,874] INFO - WebSocket opened - Token ff2c38b2-79e7-4ad5-bf01-3e859984155b
[2017-05-28 17:51:10,943] INFO - 304 GET /v1/plugins (127.0.0.1) 41.25ms
[2017-05-28 17:51:11,010] ERROR - Uncaught exception GET /v1/banks (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/v1/banks', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Referer': 'http://localhost:8100/', 'Accept-Encoding': 'gzip, deflate, sdch, br', 'Accept': 'application/json, text/plain, */*', 'Host': 'localhost:3000', 'Connection': 'keep-alive', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36', 'If-None-Match': '"e00d1c46434549bf3164172a9bc2957065710c74"', 'Origin': 'http://localhost:8100', 'Accept-Language': 'pt-BR,pt;q=0.8,en-US;q=0.6,en;q=0.4'})
Traceback (most recent call last):
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/PedalPi/lib/python3.5/site-packages/tornado/web.py", line 1467, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/webservice/webservice/handler/banks_handler.py", line 32, in get
    json = bank.json
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/model/bank.py", line 121, in json
    return self.__dict__
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/model/bank.py", line 133, in __dict__
    'pedalboards': [pedalboard.json for pedalboard in self.pedalboards]
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/model/bank.py", line 133, in <listcomp>
    'pedalboards': [pedalboard.json for pedalboard in self.pedalboards]
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/model/pedalboard.py", line 128, in json
    return self.__dict__
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/model/pedalboard.py", line 135, in __dict__
    'connections': [connection.json for connection in self.connections],
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/model/pedalboard.py", line 135, in <listcomp>
    'connections': [connection.json for connection in self.connections],
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/model/connection.py", line 97, in json
    return self.__dict__
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/model/connection.py", line 102, in __dict__
    'output': self.output.json,
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/model/output.py", line 137, in json
    return self.__dict__
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/model/lv2/lv2_output.py", line 50, in __dict__
    dictionary = super(Lv2Output, self).__dict__
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/model/output.py", line 142, in __dict__
    'effect': self.effect.index,
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/model/effect.py", line 150, in index
    return self.pedalboard.effects.index(self)
  File "/home/paulo/PycharmProjects/PedalPi-Raspberry/pluginsmanager/pluginsmanager/observer/observable_list.py", line 69, in index
    return self._list.index(x)
ValueError: <Lv2Effect object as 'Calf Reverse Delay'  active at 0x7f88d18fc0b8> is not in list
[2017-05-28 17:51:11,374] ERROR - 500 GET /v1/banks (127.0.0.1) 369.19ms
```
